### ISSUE TITLE
Crashlytics : iOS Crash : CoreFoundation : _CF_forwarding_prep_0

### ISSUE THREAD

**Issue by Nehacdew** [macmade/CoreFoundation#3]
Crash Item	:	Crashlytics : iOS Crash : CoreFoundation : _CF_forwarding_prep_0

Issue Details	:	Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9db8 __exceptionPreprocess
1  libobjc.A.dylib                0x17a68 objc_exception_throw
2  CoreFoundation                 0x17d8a4 __CFExceptionProem
3  CoreFoundation                 0x1fed0 forwarding
4  CoreFoundation                 0x87f50 _CF_forwarding_prep_0
5  UIKitCore                      0xd134 -[UIView(UIKitManual) actionForLayer:forKey:]
6  QuartzCore                     0xacb4 -[CALayer actionForKey:]
7  QuartzCore                     0xaa04 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
8  QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
9  QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
10 QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
11 QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
12 QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
13 QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
14 QuartzCore                     0xa8c0 CA::Layer::mark_visible(CA::Transaction*, bool, bool)
15 QuartzCore                     0xd287c CA::Layer::set_visible(unsigned int)
16 QuartzCore                     0x1bd0c CA::Context::set_layer(void const*)
17 UIKitCore                      0x3491e8 __UIContextBinderDisposeContextForBindable
18 UIKitCore                      0x3042a8 -[_UIContextBinder purgeContextsWithPurgeAction:afterPurgeAction:]
19 UIKitCore                      0x211d68 -[UIWindowScene _prepareForSuspend]
20 UIKitCore                      0x4adc5c -[UIScene _invalidate]
21 UIKitCore                      0x511578 -[UIWindowScene _invalidate]
22 UIKitCore                      0x47a520 -[UIApplication workspace:willDestroyScene:withTransitionContext:completion:]
23 UIKitCore                      0x468598 -[UIApplicationSceneClientAgent scene:willInvalidateWithEvent:completion:]
24 FrontBoardServices             0x1c4e0 -[FBSScene _callOutQueue_agent_willDestroyWithTransitionContext:completion:]
25 FrontBoardServices             0x20afc __84-[FBSWorkspaceScenesClient _queue_invalidateScene:withTransitionContext:completion:]_block_invoke_2
26 FrontBoardServices             0x6940 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
27 FrontBoardServices             0x1b15c __84-[FBSWorkspaceScenesClient _queue_invalidateScene:withTransitionContext:completion:]_block_invoke
28 libdispatch.dylib              0x40fc _dispatch_client_callout
29 libdispatch.dylib              0x7b7c _dispatch_block_invoke_direct
30 FrontBoardServices             0x10d88 FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK
31 FrontBoardServices             0x10924 -[FBSSerialQueue _targetQueue_performNextIfPossible]
32 FrontBoardServices             0x13104 -[FBSSerialQueue _performNextFromRunLoopSource]
33 CoreFoundation                 0xd5bd4 CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION
34 CoreFoundation                 0xe1f70 __CFRunLoopDoSource0
35 CoreFoundation                 0x65e2c __CFRunLoopDoSources0
36 CoreFoundation                 0x7b7d8 __CFRunLoopRun
37 CoreFoundation                 0x80b04 CFRunLoopRunSpecific
38 GraphicsServices               0x1360 GSEventRunModal
39 UIKitCore                      0x3a3484 -[UIApplication _run]
40 UIKitCore                      0x3a30e8 UIApplicationMain
41 TCPApp                         0xa44940 main + 39 (AppDelegate.swift:39)
42 ???                            0x25957c8f8 (Missing)
Crash Events	:	This issue has 1 crash event affecting 1 user

Device For Max count	: 	Model:iPhone 13 Pro Max
OS for Max count	:	16.0.0
Issue Occurrence : 0% Background

**Comment by Nehacdew** [comment]
@macmade  please give me a solution to this problem.

**Comment by macmade** [comment]
Maybe learn to debug your code by yourself? Or use Stackoveflow?
