### ISSUE TITLE
Crashlytics : iOS Crash : CoreFoundation -[NSOrderedSet initWithSet:copyItems:]

### ISSUE THREAD

**Issue by Nehacdew** [macmade/CoreFoundation#4]
Crash Item	:	Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x13296c __exceptionPreprocess
1  libobjc.A.dylib                0x6028 objc_exception_throw
2  CoreFoundation                 0x30dcc -[NSOrderedSet initWithSet:copyItems:]
3  UIKitCore                      0xa72c24 -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation                 0x137048 forwarding
5  CoreFoundation                 0x1393a0 _CF_forwarding_prep_0
6  UltraSDK                       0x3a698 _hidden#2304 + 52 (_hidden#2295:52)
7  libdispatch.dylib              0x1b7c _dispatch_call_block_and_release
8  libdispatch.dylib              0x2fd8 _dispatch_client_callout
9  libdispatch.dylib              0xecc8 _dispatch_main_queue_callback_4CF
10 CoreFoundation                 0xadcc8 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE
11 CoreFoundation                 0xa8a24 __CFRunLoopRun
12 CoreFoundation                 0xa7f40 CFRunLoopRunSpecific
13 GraphicsServices               0x3534 GSEventRunModal
14 UIKitCore                      0xa43a60 UIApplicationMain
15 TCPApp                         0xbad894 main + 39 (AppDelegate.swift:39)
16 libdyld.dylib                  0xe18 start
Crash Events	:	This issue has 5 crash events affecting 2 users

Device For Max count	: iPhone XS Max
OS for Max count	:	13.3.0
Issue Occurrence : 0% Background & 100% Foreground

**Comment by Nehacdew** [comment]
@macmade  give me suggestions related to this crash.

**Comment by macmade** [comment]
You probably want to debug your code by yourself…
